### ISSUE TITLE
Feather Touch destroys redstone ore and gives nothing for it.

### ISSUE THREAD

**Issue by Sedastian** [Growlith1223/ArsMagica2#102]
Not sure if anyone has had this issue.  But I cannot seem to get feather touch to give me redstone ore.  It just vanishes.

**Comment by Zieg777** [comment]
What version are you on? There was a recent update to feather touch to fix a couple bugs. Right now I'm getting redstone just fine.

**Comment by Growlith1223** [comment]
if you're not on the latest version, make sure that you are, i've done several bug fixes to the feather touch and have tested it on various blocks to check if it was working as intended and it was.

**Comment by Sedastian** [comment]
Sure enough, thank you.  Updated and it works.
