### ISSUE TITLE
current source crashes at spell creation.

### ISSUE THREAD

**Issue by shadow-absorber** [Growlith1223/ArsMagica2#106]
@Growlith1223 

when you throw the spell parchment to complete a spell creation in the current source version the game crashes with a model error.

**Comment by sam-tunder** [comment]
will attach crash report soon

**Comment by shadow-absorber** [comment]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/17/16 9:10 PM
Description: Rendering item

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at am2.items.rendering.SpellRenderer.getModelLocation(SpellRenderer.java:84)
	at net.minecraft.client.renderer.ItemModelMesher.getItemModel(ItemModelMesher.java:52)
	at net.minecraft.client.renderer.RenderItem.getItemModelWithOverrides(RenderItem.java:253)
	at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:356)
	at net.minecraft.client.gui.GuiIngame.renderHotbarItem(GuiIngame.java:1144)
	at net.minecraft.client.gui.GuiIngame.renderHotbar(GuiIngame.java:528)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:329)
	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:140)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1125)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1139)
	at net.minecraft.client.Minecraft.run(Minecraft.java:406)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at am2.items.rendering.SpellRenderer.getModelLocation(SpellRenderer.java:84)
	at net.minecraft.client.renderer.ItemModelMesher.getItemModel(ItemModelMesher.java:52)
	at net.minecraft.client.renderer.RenderItem.getItemModelWithOverrides(RenderItem.java:253)

-- Item being rendered --
Details:
	Item Type: am2.items.SpellBase@62765e11
	Item Aux: 0
	Item NBT: {AM2:{ShapeGroups:[0:{CurrentGroup:0,Stage_0:[0:{Type:"Shape",ID:"arsmagica2:projectile"}],SpellData:{},LastWasShape:1b,StageNum:1}],CurrentGroup:0,Stage_0:[0:{Type:"Component",ID:"arsmagica2:physical_damage"}],NumShapeGroups:1,SpellData:{},CurrentShapeGroup:0,StageNum:1},suggestedName:""}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:356)
	at net.minecraft.client.gui.GuiIngame.renderHotbarItem(GuiIngame.java:1144)
	at net.minecraft.client.gui.GuiIngame.renderHotbar(GuiIngame.java:528)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:329)
	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:140)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player196'/773, l='MpServer', x=117.18, y=70.00, z=233.15]]
	Chunk stats: MultiplayerChunkCache: 540, 540
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (144,64,244), Chunk: (at 0,4,4 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 837 game time, 837 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntityBat['Bat'/4144, l='MpServer', x=77.61, y=44.72, z=200.43], EntityBat['Bat'/4145, l='MpServer', x=100.00, y=39.05, z=200.43], EntityChicken['Chicken'/101, l='MpServer', x=61.50, y=63.00, z=169.50], EntityChicken['Chicken'/102, l='MpServer', x=60.50, y=63.00, z=168.50], EntityChicken['Chicken'/103, l='MpServer', x=60.50, y=63.00, z=170.50], EntityChicken['Chicken'/104, l='MpServer', x=63.50, y=63.00, z=171.50], EntityChicken['Chicken'/124, l='MpServer', x=102.50, y=65.00, z=167.50], EntityChicken['Chicken'/125, l='MpServer', x=103.50, y=65.00, z=166.50], EntityChicken['Chicken'/126, l='MpServer', x=101.50, y=65.00, z=166.50], EntityChicken['Chicken'/127, l='MpServer', x=99.50, y=64.00, z=167.50], EntityChicken['Chicken'/128, l='MpServer', x=88.13, y=71.00, z=219.62], EntityChicken['Chicken'/129, l='MpServer', x=89.49, y=71.73, z=220.54], EntityChicken['Chicken'/130, l='MpServer', x=105.21, y=76.00, z=213.53], EntityChicken['Chicken'/131, l='MpServer', x=93.86, y=74.00, z=219.51], EntityChicken['Chicken'/132, l='MpServer', x=111.50, y=71.00, z=222.50], EntityChicken['Chicken'/133, l='MpServer', x=89.87, y=77.00, z=239.51], EntityChicken['Chicken'/134, l='MpServer', x=111.58, y=70.00, z=224.89], EntityChicken['Chicken'/135, l='MpServer', x=108.59, y=71.00, z=230.70], EntityChicken['Chicken'/147, l='MpServer', x=135.50, y=71.00, z=179.50], EntityChicken['Chicken'/148, l='MpServer', x=135.50, y=70.00, z=180.50], EntityChicken['Chicken'/149, l='MpServer', x=134.50, y=71.00, z=180.50], EntityChicken['Chicken'/150, l='MpServer', x=124.40, y=86.00, z=175.12], EntityChicken['Chicken'/151, l='MpServer', x=122.50, y=72.00, z=212.50], EntityChicken['Chicken'/152, l='MpServer', x=132.15, y=69.00, z=218.81], EntityChicken['Chicken'/153, l='MpServer', x=124.90, y=70.00, z=222.80], EntityChicken['Chicken'/154, l='MpServer', x=139.46, y=64.00, z=216.64], EntityChicken['Chicken'/155, l='MpServer', x=133.79, y=69.00, z=231.51], EntityChicken['Chicken'/156, l='MpServer', x=120.67, y=70.00, z=231.88], EntityChicken['Chicken'/157, l='MpServer', x=131.39, y=69.00, z=243.87], EntityChicken['Chicken'/158, l='MpServer', x=124.81, y=70.00, z=243.40], EntityCow['Cow'/166, l='MpServer', x=142.50, y=69.00, z=170.50], EntityCow['Cow'/167, l='MpServer', x=149.46, y=65.00, z=160.79], EntityCow['Cow'/168, l='MpServer', x=142.50, y=68.00, z=172.50], EntityCow['Cow'/169, l='MpServer', x=145.50, y=64.00, z=174.50], EntityChicken['Chicken'/170, l='MpServer', x=140.23, y=68.00, z=297.42], EntityChicken['Chicken'/171, l='MpServer', x=139.50, y=67.00, z=306.50], EntityChicken['Chicken'/172, l='MpServer', x=137.50, y=67.00, z=309.50], EntityChicken['Chicken'/173, l='MpServer', x=143.50, y=65.00, z=307.50], EntityChicken['Chicken'/174, l='MpServer', x=148.50, y=64.00, z=307.50], EntityChicken['Chicken'/175, l='MpServer', x=150.50, y=63.00, z=308.50], EntityChicken['Chicken'/176, l='MpServer', x=144.50, y=65.00, z=306.50], EntityChicken['Chicken'/177, l='MpServer', x=143.50, y=64.00, z=305.50], EntityCreeper['Creeper'/4329, l='MpServer', x=77.50, y=55.00, z=183.50], EntityCreeper['Creeper'/4330, l='MpServer', x=80.50, y=55.00, z=184.50], EntitySkeleton['Skeleton'/4360, l='MpServer', x=42.50, y=47.00, z=279.50], EntitySkeleton['Skeleton'/4361, l='MpServer', x=45.50, y=47.00, z=279.50], EntitySkeleton['Skeleton'/4362, l='MpServer', x=44.50, y=47.00, z=279.50], EntitySkeleton['Skeleton'/4379, l='MpServer', x=85.50, y=18.00, z=246.50], EntitySkeleton['Skeleton'/4402, l='MpServer', x=73.50, y=45.00, z=264.50], EntitySkeleton['Skeleton'/4417, l='MpServer', x=46.66, y=20.00, z=215.50], EntityWitch['Witch'/4418, l='MpServer', x=46.50, y=18.00, z=247.50], EntitySkeleton['Skeleton'/4441, l='MpServer', x=38.50, y=19.00, z=231.50], EntitySkeleton['Skeleton'/4442, l='MpServer', x=39.50, y=19.00, z=229.50], EntityCreeper['Creeper'/4489, l='MpServer', x=136.50, y=44.00, z=273.50], EntityZombie['Zombie'/4562, l='MpServer', x=118.50, y=21.00, z=255.50], EntitySkeleton['Skeleton'/4563, l='MpServer', x=118.50, y=21.00, z=255.50], EntitySkeleton['Skeleton'/4564, l='MpServer', x=118.50, y=21.00, z=255.50], EntityZombie['Zombie'/4689, l='MpServer', x=49.50, y=54.00, z=166.50], EntityZombie['Zombie'/4690, l='MpServer', x=49.50, y=54.00, z=167.50], EntityZombie['Zombie'/4691, l='MpServer', x=49.50, y=54.00, z=166.50], EntityCreeper['Creeper'/4692, l='MpServer', x=50.50, y=54.00, z=166.50], EntityCreeper['Creeper'/4717, l='MpServer', x=62.50, y=35.00, z=219.50], EntityCreeper['Creeper'/4718, l='MpServer', x=60.60, y=35.00, z=219.85], EntityZombie['Zombie'/4732, l='MpServer', x=163.50, y=30.00, z=230.50], EntityZombie['Zombie'/4741, l='MpServer', x=43.50, y=58.00, z=275.50], EntityZombie['Zombie'/4745, l='MpServer', x=115.50, y=18.00, z=193.50], EntityZombie['Zombie'/4746, l='MpServer', x=115.50, y=18.00, z=192.50], EntityZombie['Zombie'/4747, l='MpServer', x=115.50, y=18.00, z=191.50], EntityCreeper['Creeper'/4773, l='MpServer', x=78.50, y=48.00, z=175.50], EntityCreeper['Creeper'/4774, l='MpServer', x=79.50, y=48.00, z=173.50], EntityCreeper['Creeper'/4800, l='MpServer', x=59.50, y=54.00, z=235.50], EntitySkeleton['Skeleton'/4844, l='MpServer', x=74.50, y=46.00, z=162.50], EntityZombie['Zombie'/4886, l='MpServer', x=94.50, y=65.00, z=220.50], EntityZombie['Zombie'/4887, l='MpServer', x=92.50, y=65.00, z=223.50], EntityPlayerSP['Player196'/773, l='MpServer', x=117.18, y=70.00, z=233.15], EntityCreeper['Creeper'/2718, l='MpServer', x=93.50, y=64.00, z=220.30], EntityCreeper['Creeper'/2723, l='MpServer', x=90.30, y=63.00, z=215.09], EntityCreeper['Creeper'/2727, l='MpServer', x=84.79, y=62.00, z=212.50], EntityFlicker['entity.arsmagica2.Flicker.name'/2741, l='MpServer', x=81.25, y=69.50, z=258.50], EntitySkeleton['Skeleton'/3094, l='MpServer', x=163.50, y=30.00, z=222.50], EntityCreeper['Creeper'/3338, l='MpServer', x=59.82, y=58.00, z=192.51], EntityEnderman['Enderman'/3339, l='MpServer', x=73.50, y=16.00, z=238.50], EntityCreeper['Creeper'/3878, l='MpServer', x=65.50, y=51.00, z=177.50], EntityFlicker['entity.arsmagica2.Flicker.name'/3888, l='MpServer', x=57.85, y=80.78, z=227.02], EntityCreeper['Creeper'/3955, l='MpServer', x=66.50, y=47.00, z=272.50], EntityCreeper['Creeper'/3969, l='MpServer', x=143.50, y=41.00, z=270.50], EntityCreeper['Creeper'/3970, l='MpServer', x=140.50, y=41.00, z=270.50], EntitySkeleton['Skeleton'/3973, l='MpServer', x=142.50, y=41.00, z=268.50], EntitySkeleton['Skeleton'/3974, l='MpServer', x=140.50, y=41.00, z=268.50], EntitySkeleton['Skeleton'/3998, l='MpServer', x=79.50, y=27.00, z=181.50], EntityZombie['Zombie'/4002, l='MpServer', x=68.50, y=14.00, z=183.50], EntityBat['Bat'/4010, l='MpServer', x=98.63, y=37.16, z=201.84], EntityBat['Bat'/4011, l='MpServer', x=101.08, y=36.15, z=200.25], EntityBat['Bat'/4012, l='MpServer', x=100.14, y=38.06, z=200.27], EntityBat['Bat'/4036, l='MpServer', x=62.75, y=45.10, z=270.75], EntityBat['Bat'/4041, l='MpServer', x=176.71, y=26.44, z=242.45], EntityFlicker['entity.arsmagica2.Flicker.name'/4042, l='MpServer', x=82.25, y=18.50, z=255.75], EntityFlicker['entity.arsmagica2.Flicker.name'/4043, l='MpServer', x=82.25, y=18.50, z=255.75], EntityItem['item.tile.gravel'/4062, l='MpServer', x=178.88, y=24.00, z=243.88]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:451)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2779)
	at net.minecraft.client.Minecraft.run(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.8.0-30-generic
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 549087024 bytes (523 MB) / 1175453696 bytes (1121 MB) up to 1836580864 bytes (1751 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forgeSrc-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	arsmagica2{GRADLE:VERSIONGRADLE:BUILD} [Ars Magica 2] (bin) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (bin) 
	UCHIJAAAA	JEI{3.7.8.235} [Just Enough Items] (jei_1.10.2-3.7.8.235.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0-deobf.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 367.57' Renderer: 'GeForce GT 740M/PCIe/SSE2'
	Launched Version: 1.10.2
	LWJGL: 2.9.4
	OpenGL: GeForce GT 740M/PCIe/SSE2 GL version 4.5.0 NVIDIA 367.57, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz

**Comment by Growlith1223** [comment]
fixed somewhat, i haven't tested on windows however, so if it persists on windows, just lemme know!

**Comment by shadow-absorber** [comment]
i am sorry i can't test for windows either as i only use linux but atleast it dosent crash any more!
