### ISSUE TITLE
[Curse] Permission to use in curse modpacks.

### ISSUE THREAD

**Issue by Yankas** [Growlith1223/ArsMagica2#108]
Would you mind if the pack is added to the curse forge [third party list](https://docs.google.com/spreadsheets/d/1BX4fFRnfANPvWjnkPlfGx03RlBq5JkmuBvwEO_6gdbE/edit), allowing mod pack makers to distribute this mod in their packs?

**Comment by Growlith1223** [comment]
regarding this, i've tried adding it before, it got denied due to Ars Magica being already added as an official mod on the curse site. i've contacted Mithion about allowing me to post it as an unofficial mod but until then, you might be stuck with packs from like, AT Launcher or Technic
