### ISSUE TITLE
Server crash on startup please help

### ISSUE THREAD

**Issue by TCBPlays** [Growlith1223/ArsMagica2#114]
here is the pastebin please help server crashed on startup

http://pastebin.com/EsXaavFG

EDIT: seems to happen even when its the only one in mods folder

**Comment by PokeMaserJ** [comment]
I see you have Ars Magica 2 1.5.0-8. Get Ars Magica 2 1.5.0-9, that has a hot fix for server crashing. Actually, you should get Ars Magica 2 1.5.0-11 to fix a fair amount of bugs, like Dig component duping blocks.

**Comment by Growlith1223** [comment]
you are using an outdated version, make sure you are on the latest version.
