### ISSUE TITLE
Re-occuring Server crash - CME

### ISSUE THREAD

**Issue by Saereth** [Growlith1223/ArsMagica2#115]
Ars Magica 2 1.5.0-15 (also occurs with v11, v9, v8)
Forge 1.10.2 - 12.18.3.2185

Every few days we seem to get a CME on our server with Ars Magica installed. Currently on the latest available download from your release page, but this issue has been present since v9 or perhaps earlier. We've removed many mods to troubleshoot with no luck. We cant seem to consistently reproduce it or avoid it. 

The first time it happened we noticed the crash when a certain player logged in. Setting his location to spawn didnt fix it, resetting his player data did. The last two crashes we just rolled back to a previous save (we do 30 min incremental backups). 

Here is the full crashlog, Let me know if there is anything more I can do to help troubleshoot this, CME's are a pain -_-

https://hastebin.com/zeqotimiri.sql

**Comment by Growlith1223** [comment]
im aware of this, im honestly not sure why it happens, i know it only occurs with The One Probe however.

**Comment by Growlith1223** [comment]
i should make a list of bugs...

**Comment by Growlith1223** [comment]
i am happy to say, that this is finally fixed!

**Comment by Growlith1223** [comment]
I will also be releasing a hotfix right now as well

**Comment by Gaelan** [comment]
This is still happening for me for me on .15. Happens whenever one player logs in. My crash: https://gist.github.com/Gaelan/7bced5a4183b2b10fe02e7b2dce3b01a

EDIT: I thought the affected player was in the end, but it turns out they are not. Seems like some chunks are broken in some way, as other players can log in fine.
