### ISSUE TITLE
mana batteries

### ISSUE THREAD

**Issue by wolfbain5** [Growlith1223/ArsMagica2#117]
they don't seem to be charging. when I use the wrench it says link successful, but it doesn't store energy. It also when used in a chain from obelisk to battery to say the essence refiner, the energy isn't passing through the battery either.

**Comment by PokeMaserJ** [comment]
Mana Batteries need a lever on them to be able to charge.

**Comment by Orinion** [comment]
For me the[ magitech Staff](https://github.com/EdwinMindcraft/ArsMagica2/blob/master/src/main/java/am2/items/ItemSpellStaff.java#L246) shows the etherium perfectly, however the charge level [when rightclicking](https://github.com/EdwinMindcraft/ArsMagica2/blob/master/src/main/java/am2/blocks/BlockManaBattery.java#L68) stays at 0%.
The PowerType is correctly.

**Comment by Orinion** [comment]
The only difference is the world object:
with the Staff the WorldServer gets passed, when rightclicking you get the WorldClient.

**Comment by Growlith1223** [comment]
What version, im going to start closing some of these if you don't say the version lol

**Comment by Orinion** [comment]
tested in 1.10.2

**Comment by Growlith1223** [comment]
i didn't ask for the minecraft version, i asked for the Mod Version.

**Comment by Orinion** [comment]
i build it from the latest git commit
Also tested in 1.5.0-15, forge 12.18.3.2185, for the solution check my pull request. Appeared in Singleplayer.
