### ISSUE TITLE
projectile dig

### ISSUE THREAD

**Issue by wolfbain5** [Growlith1223/ArsMagica2#118]
1 shot is removing 3 blocks. just projectile dig, no piercing

**Comment by ProfHugo** [comment]
Can you provide more info and details regarding the bug you're encountering, such as version number, individual steps in reproducing it, probability in occurrence, etc?

**Comment by Growlith1223** [comment]
closed until sufficient information is given.

**Comment by ProfHugo** [comment]
I think I know what's up... Apparently the fix applied to piercing had a slight problem where it would apply one level of piercing by default, resulting in any projectile spells hitting 3 targets without any piercing modifiers. That said, if you have max level piercing, it would hit a total of 9 targets, so there's that. I'm going to open up a new issue regarding this for documentation.

**Comment by wolfbain5** [comment]
ah, sorry was away from comp for a couple of days, version 15, reproduced every time, remade the spell, still does it. yeah looks like it is piercing.

**Comment by Growlith1223** [comment]
don't worry about it, i've fixed it in the code, i'll post a new update around the first!
