### ISSUE TITLE
1.5.0-15: One level of piercing automatically applied to any projectile spells

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#121]
This is the same issue as #118 , where a spell without any piercing modifier would ended up hitting 3 targets anyways as if it has one level of piercing. With more piercing modifiers the hit count would just go up as usual. 

Intended:
0 Modifier: 1 target 
1 Modifier: 3 targets
2 Modifiers: 5 targets
3 Modifiers: 7 targets

1.5.0-15 Piercing:
0 Modifier: 3 target 
1 Modifier: 5 targets
2 Modifiers: 7 targets
3 Modifiers: 9 targets

**Comment by Orinion** [comment]
This is probably because of https://github.com/Growlith1223/ArsMagica2/commit/44173cceeea12ef424883ef45d8237b5bc3ba43b

**Comment by Growlith1223** [comment]
i didn't really see this issue when i was testing but i'll check it out.

**Comment by Growlith1223** [comment]
fixed!
