### ISSUE TITLE
[1.5.0-15] - mana martini crashes server

### ISSUE THREAD

**Issue by knoxhack** [Growlith1223/ArsMagica2#127]
"Yeah, the title... Drinking mana martini crashes the server.
Using forge-12.18.3.2185
And using MMD Project Ultimate 1.3"

From: https://github.com/MinecraftModDevelopment/Project-Ultimate/issues/15

Crash report:(server side)
https://gist.github.com/knoxhack/bafc07c4ff73d47d725f7d6d97c569af

**Comment by knoxhack** [comment]
https://github.com/MinecraftModDevelopment/Project-Ultimate/issues/15

**Comment by knoxhack** [comment]
https://github.com/rwtema/extrautilities/issues/1191

**Comment by EPIICTHUNDERCAT** [comment]
This also happened in Hypothermia, But i believe it was a client crash.

**Comment by Orinion** [comment]
http://i.imgur.com/ERIw69g.png
for some reason during startup, the Manamartini gets created before the burnoutReduction Potioneffect.
