### ISSUE TITLE
block model crash while starting mc.

### ISSUE THREAD

**Issue by Divineaspect** [Growlith1223/ArsMagica2#131]
This is the last mod to load before getting a block model baking crash.

Largely uphelpful crashlog for completeness
http://pastebin.com/jtd6JrPK

http://paste.atlauncher.com/view/360808b5
Starting on line 17

**Comment by Divineaspect** [comment]
I'm doing ongoing testing on this and will update if I can eliminate am2 from triggering this.

**Comment by Divineaspect** [comment]
ok, I can eliminate AM2 from being the culprit here, it's one of several mods which can cause the problem but  only in combination with harder farming.

**Comment by EPIICTHUNDERCAT** [comment]
What version of Ars? if it's the latest it may not be Ars, I haven't heard of this error from anyone yet. Growlith will look into it!

**Comment by EPIICTHUNDERCAT** [comment]
hmm interesting

**Comment by Divineaspect** [comment]
-15 we always reproduce with the newest one before reporting.
