### ISSUE TITLE
1.5.0-15: Dig Balance Request

### ISSUE THREAD

**Issue by mr-poyo** [Growlith1223/ArsMagica2#137]
Hello,

When I craft a basic projectile dig spell, it is pretty darn strong. 

It mines more than one block every time, which makes precision digging difficult. Also, the burnout barely moves with Dig after the initial cast. Hope this helps for future balance updates!

Very Respectfully,

Cliff

**Comment by Growlith1223** [comment]
this is already fixed, i just haven't posted a new update yet
