### ISSUE TITLE
Crafting Altar block is broken instantly with no tool in survival mode

### ISSUE THREAD

**Issue by Febilian** [Growlith1223/ArsMagica2#14]
I accidentally punched it and now I have to make another one. Oops.

Pretty sure it was supposed to be breakable only by a pickaxe, so I thought I'd let you know.

EDIT: Never mind, just saw this in the closed issues. Should've checked there first!

**Comment by Growlith1223** [comment]
i'm going to release a new download soon(downloads will be under the release section!) but yes, this has been fixed.

**Comment by Divineaspect** [comment]
Which release section?
