### ISSUE TITLE
Getting information you need/want in inital posts.

### ISSUE THREAD

**Issue by Divineaspect** [Growlith1223/ArsMagica2#140]
Perhaps setup a CONTRIBUTING.md file, and maybe a base ISSUE_TEMPLATE with the questions you want, such as making sure it's with the most recent version, that people tell you what version it's on.

**Comment by Orinion** [comment]
well ther is [this ](http://pastebin.com/29r0Nhe0) in the README.md

**Comment by Growlith1223** [comment]
![image](https://cloud.githubusercontent.com/assets/5291393/21662414/5ac68d8a-d28e-11e6-9d03-ccab3e16d745.png)

on the readme.MD

**Comment by Divineaspect** [comment]
frankly it's out of the way, and appears as an artifact from earlier devs. *shrug*

**Comment by Growlith1223** [comment]
it's literally on the front page, it only requires a bit of scrolling lol
