### ISSUE TITLE
[1.5.0-15] -Slipstream Generator operates in reverse?

### ISSUE THREAD

**Issue by Sedastian** [Growlith1223/ArsMagica2#141]
Latest build, slipstream goes up by looking down, goes down by looking up.  Anyone else having this issue?

**Comment by EPIICTHUNDERCAT** [comment]
I know we know what the latest build is, but saying latest changes over time. Please specify version number on your posts.

**Comment by Sedastian** [comment]
1.5.0-15.

I believe it's been this way since 1.5.0-09 as well.

**Comment by Orinion** [comment]
fixed @Growlith1223
