### ISSUE TITLE
[Suggestion] Make Witchwood burn

### ISSUE THREAD

**Issue by LordAzazel** [Growlith1223/ArsMagica2#145]
Witchwood logs/planks can't be used a fuel in furnaces or used to create charcoal, this isn't a bug because it was in the 1.7.10 version as well. I'm posting this because I think it's odd that witchwood is the only wood that can't do this.

**Comment by Sedastian** [comment]
Can use minetweaker (crafttweaker for 1.10.x) and the command added to the script (filename.zs)

furnace.setFuel(<<arsmagica2:witchwood_log>>, 100);
furnace.setFuel(<<arsmagica2:witchwood_planks>>, 50);

To make them be burned into charcoal (or coal) just add

For coal
furnace.addRecipe(<<minecraft:coal:0>>, <<arsmagica2:witchwood_log>>);  
For charcoal
furnace.addRecipe(<<minecraft:coal:1>>, <<arsmagica2:witchwood_log>>);

Or, of course, you could just modify the ore dictionary...but that has baffled me and broken things, so I usually leave that alone.  :P

**Comment by Growlith1223** [comment]
added by Orinion
