### ISSUE TITLE
OH DEAR STILL IN 1.5.0-17: Missing Spell Icons During Selection

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#146]
I'm highly suspicious that 954ced8 broke the spell icon selector for Windows, and....

CHECKERBOARDS:
![2017-01-06_16 18 15](https://cloud.githubusercontent.com/assets/23370942/21737264/154c32e2-d42c-11e6-97ff-2169accb6dc9.png)

A fix to Linux is poison to Windows they said

"this SHOULD be the final fix i need to do for it" nope still busted. Reverting that patch partially fixes it on Windows, but well...

LESS CHECKERBOARDS:
![2017-01-06_16 47 12](https://cloud.githubusercontent.com/assets/23370942/21737663/d1b1034c-d42f-11e6-9c55-ad54496feb3c.png)
Still looks busted.

*This is on Windows 10 64bit

**Comment by Orinion** [comment]
i reverted the commit locally but it was still broken for me on windows

**Comment by Orinion** [comment]
For some reason now it's working
![](http://i.imgur.com/IvUTsWx.png)

**Comment by Growlith1223** [comment]
so can anyone confirm this is actually working?

**Comment by ProfHugo** [comment]
Can confirm, still as broken as it can ever be. 

I made a minor mistake while reverting the patch the last time I tested it, so reverting patch 954ced8 actually completely fixes the issue on Windows.

What was this patch for again? Was it something broken in Linux?

**Comment by ProfHugo** [comment]
For now, I think it's better to just revert patch 954ced8 until there's a solution for both operating systems. I don't know what went up on linux's side, but somehow JVM ain't doing its job well, and with this patch it's now busted on Windows. I felt like the temporary fix on linux at the cost of rendering this mob unusable for Windows just doesn't cut it...

Before revert:  
![2017-02-04_22 00 50](https://cloud.githubusercontent.com/assets/23370942/22624331/d0208f60-eb2d-11e6-8cbb-43d936c69b5e.png)

After revert:
![2017-02-04_23 16 56](https://cloud.githubusercontent.com/assets/23370942/22624408/0f62d348-eb30-11e6-8581-92c37feb2455.png)

**Comment by camilla-ett** [comment]
send PR #177

**Comment by ProfHugo** [comment]
Fixed thanks to @camilla-ett
