### ISSUE TITLE
[1.5.0-15] - Server Error messages re Mobs

### ISSUE THREAD

**Issue by Zygus42** [Growlith1223/ArsMagica2#153]
vArsMagica2-1.10.2-1.5.0-15
forge: 1.10.2-12.18.3.2185
Getting a ton of error messages re Ars mobs on server:

[Ars Problem.zip](https://github.com/Growlith1223/ArsMagica2/files/703467/Ars.Problem.zip)

**Comment by EPIICTHUNDERCAT** [comment]
Yes, this is known, its nothing harmful just a spam warning.

**Comment by Growlith1223** [comment]
as Epiic had said, they do nothing, don't worry about them.
