### ISSUE TITLE
I want to have ars in my pack on Curse but they're saying it's not allowed to be redistributed

### ISSUE THREAD

**Issue by MrTubzy456** [Growlith1223/ArsMagica2#155]
as it says in the title, I want Ars in my pack here: https://minecraft.curseforge.com/members/MrTubzy

When I first uploaded my pack it was fine but, when I went to update my pack they rejected my files because of ars. Do I need anything special from you guys?

**Comment by TheIcyOne** [comment]
#122 would suggest that this shouldn't be the case, are you using the version from Curse?

**Comment by EPIICTHUNDERCAT** [comment]
@MrTubzy456 My suggestion is to upload ars disabled. that allows you to upload it, atleast it worked for us.

**Comment by renadi** [comment]
Hah, you shouldn't be able to do that...

Growlith isn't allowed to add Ars Magica to the approved list because it is
already on curse, and isn't willing to upload a build to curse yet because
of issues still existing.

**Comment by MrTubzy456** [comment]
no I used the one from, the one on curse 1.7.10. I thought I'd be ok because Ars is open source,

**Comment by MrTubzy456** [comment]
I'll try uploading with it disabled.

**Comment by EPIICTHUNDERCAT** [comment]
yep our pack does it that way, "Hypothermia" so you should.

**Comment by MrTubzy456** [comment]
Thanks, trying that now.

**Comment by MrTubzy456** [comment]
It worked but, I wanna hear from Growlith so I know the legit way of doing this because right now it just feels like I'm doing some kind of workaround.

**Comment by MrTubzy456** [comment]
Due to no response from the author and Curse still harassing me about this issue I'm just removing this from my pack and closing this issue.

**Comment by Growlith1223** [comment]
didn't see this post honestly, my bad, and regarding the usage of these versions, i wouldn't really suggest doing so until i post a dl on the curse project, these were meant as test releases, what you see is what you get, the curse download will have the majority of the bugs that are currently known, fixed, or at least hopefully... lol
