### ISSUE TITLE
AM2 1.5.0-15 Deconstructor not functioning properly.

### ISSUE THREAD

**Issue by Lonemind** [Growlith1223/ArsMagica2#157]
The Deconstructor seems to no longer break down items. The only time I have been able to make it successful is by breaking down a spell that has so many ingredients that it forces the deconstructor to eject items into the world. (Which, in itself, is a bug I think.)
It would be nice if it would eject everything into an adjacent container. I've been using a hopper until now.

**Comment by TheIcyOne** [comment]
It already ejects items into adjacent chests.
