### ISSUE TITLE
Feather touch does not work

### ISSUE THREAD

**Issue by the-realest-stu** [Growlith1223/ArsMagica2#16]
Blocks still drop their usual drops, even when feather touch is in the spell

**Comment by Zieg777** [comment]
Only way it semi works is by punching a block with it. I can get grass etc, but I cant silk touch mine.

**Comment by Growlith1223** [comment]
i could be wrong but i believe the feather touch never worked at all? if anyone could test this, would be appreciated, regardless, im working on a fix atm

**Comment by Zieg777** [comment]
It used to work on 1.7.10. Only way I can get it to somewhat work is like I said, Punching a block with the spell equipped. The spell itself (in this case projectile or projectile AOE dig) when it hits just turns smooth stone to cobble.

**Comment by Growlith1223** [comment]
alright, yea i'll get it fixed, should be fixed in next version!

**Comment by Zieg777** [comment]
I just want to say thank you so much. I know you've been flooded with bug reports since releasing. Thank you

**Comment by Growlith1223** [comment]
lol no problem and it's fine there's so many bug reports, i don't really mind lol

**Comment by Growlith1223** [comment]
fixed!

**Comment by Zieg777** [comment]
Yay! Thank you!

Now to see if i can remember how to compile the jar from github..

**Comment by Growlith1223** [comment]
lol i'll throw a download up soon
