### ISSUE TITLE
[1.5.0-15] Concurrent Modification Exception

### ISSUE THREAD

**Issue by StarkRG** [Growlith1223/ArsMagica2#162]
Apparently the player flew into a biome (his words) and it caused the server to crash. After restarting he logged in and it crashed again. The coordinates are in there and I sent another player to them and the server crashed again.

Logs galore:
[crash-2017-01-22_03.13.44-client.txt](https://github.com/Growlith1223/ArsMagica2/files/722745/crash-2017-01-22_03.13.44-client.txt)
[2017-01-23-5.log.txt](https://github.com/Growlith1223/ArsMagica2/files/722748/2017-01-23-5.log.txt)
[fml-server-3.log.txt](https://github.com/Growlith1223/ArsMagica2/files/722749/fml-server-3.log.txt)

**Comment by Growlith1223** [comment]
this crash log is regarding the hand rake, which is not from ars magica, more importantly the crash log says refined storage, i would contact the author of that mod

**Comment by StarkRG** [comment]
Whoops, sorry, grabbed the wrong report, that's even a client crash log not server. 

Here's the correct one:
[crash-2017-01-23_00.38.12-server.txt](https://github.com/Growlith1223/ArsMagica2/files/722958/crash-2017-01-23_00.38.12-server.txt)

**Comment by Growlith1223** [comment]
there ya go lol, thanks for letting me know, i'll check it out

**Comment by Growlith1223** [comment]
https://www.dropbox.com/s/ggjarr5qgivnbd6/ArsMagica2-1.10.2-1.5.0-16a.jar?dl=0

See if this fixes the issue

**Comment by Growlith1223** [comment]
im going to assume this is fixed so im going to close this.
