### ISSUE TITLE
Curseforge Third Party Mod

### ISSUE THREAD

**Issue by Waisse** [Growlith1223/ArsMagica2#168]
I'd like to know if this fork is ok with being added to the Third Party Mod list : https://docs.google.com/spreadsheets/d/1lEwbJpwRVoZb8kr0OT-Wo4Yc7jAGWMGOFtfL0miCFmc/edit#gid=0](url

I'm not sure if this fork meet every requirement listed here : https://www.curseforge.com/knowledge-base/minecraft/120-minecraft-modpack-submission

Does it ? I'd like to use this fork in my public pack.

**Comment by Valchap** [comment]
This mod is licensed "Creative Commons 3.0 Non-Commercial Attribution".
So if you give the credits to Growlight and Mithion I think you can.
But it's better to wait for a confirmation from Growlight.

**Comment by Sunconure11** [comment]
@valentin616 Curse does not accept personal permissions.

**Comment by Valchap** [comment]
You're right. They refuse mods with credits.

Let's wait for the mod to be officially added to CurseForge

**Comment by thephoenixlodge** [comment]
From the submissions page linked by OP:
"The mod must be licensed as MIT/GPL or an equivalent. A blurb on their webpage saying "You can use this in anything including packs" will suffice as long as there are **no conditions beyond credit** attached.
The mod's open use policy is **not conditional beyond requiring credit.** Mods with "link back", "text file credit", or other requirements will not be considered."

Credit requirement is fine. Anything more than that isn't.

**Comment by xenxero1** [comment]
I'd really like to see this used in my pack as well. I'm wondering if @Growlith1223 has had any plans to do so, if not fully host it on curseforge. If it's planned, an ETA would be greatly appreciated!

On second review, I'm not sure if the Creative Commons License qualifies for CurseForge.

**Comment by Growlith1223** [comment]
i'll be releasing a version within a couple hours as i fix up a couple of game-breaking bugs so it's at least somewhat presentable
