### ISSUE TITLE
Sponge Issues

### ISSUE THREAD

**Issue by ElvenChaos** [Growlith1223/ArsMagica2#17]
Not sure if this is reasonably fixable, but having AM2 and Sponge for Forge on a server creates an error where sponge can't edit a particular class due to it being "prematurely loaded," according to it.

Here is a paste from my fml-server-latest log regarding the issue.
http://pastebin.com/UdnkCBh7

MC 1.10.2
Forge 2122
Sponge 1874
AM2 1.5.0_6

**Comment by liach** [comment]
https://github.com/Growlith1223/ArsMagica2/blob/1.10.2/src/main/java/am2/asm/Preloader.java#L16

For compatibility with Sponge, Coremod class and mod container class should be separated.

**Comment by Growlith1223** [comment]
haven't tested fully but im not getting any crashes anymore by doing what Liach has specified(also went and looked at other mods to see what they done with their preloaders and they do the same thing) so if there's any issues, im going to leave this up for now

**Comment by Growlith1223** [comment]
so can anyone confirm that this is working now??

**Comment by EPIICTHUNDERCAT** [comment]
Bumping this, @ElvenChaos or @liach is this working now or still broken?

**Comment by ElvenChaos** [comment]
My apologies, I didn't see the last two bumps (my email gets flooded with messages from AM2 Issues, I need to fix my settings). I can confirm that these issues have been long corrected.

**Comment by EPIICTHUNDERCAT** [comment]
Thank you!
