### ISSUE TITLE
[1.10.2][1.5.0-17] Unmodified Dig component unable to mine stone or harder materials

### ISSUE THREAD

**Issue by Not-February** [Growlith1223/ArsMagica2#173]
It's working fine on dirt, clay and wood - basically anything that can be dug out with your bare hands - while the compendium still states that it should be equivalent to an iron pickaxe, but it can't even mine normal stone, let alone ores an iron pickaxe should be able to.

I should note that before I updated to this version, it was working as expected(i.e. it could dig anything an iron pickaxe could). Was Dig nerfed and the change was simply undocumented or did something go wrong?

I tried re-making the projectile dig spell in creative mode in case something was wrong with the spell itself, to no difference.

I also should note I'm playing on a dedicated private server, don't know if it works in single player.

**Comment by Valchap** [comment]
It also does not work with mining power.

**Comment by Not-February** [comment]
I hadn't gotten around to testing that part yet; good catch.

**Comment by Orinion** [comment]
i don't know why it appears now, but the issue is that in 
`\net\minecraftforge\common\ForgeHooks.java` in line 174 the toollevel is -1 resulting in only letting the player harvest things he can by hand.
