### ISSUE TITLE
1.5.0-17: Dryad Orgy, Anywhere, Everywhere (Insane Spawnrate)

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#174]
I know there is still a WIP fix to dryads not spawning, but imma just put this here, as the spawnrate in the most recent version right now is just beyond insane....

WOO HOO IT'S A PARTY
![2017-02-04_22 01 08](https://cloud.githubusercontent.com/assets/23370942/22624079/e914a14e-eb25-11e6-8383-7bcebfeb701d.png)

Note: This is after roaming in and out of the area, the spawnrate isn't that insane, but rather more like this:
![2017-02-04_22 06 42](https://cloud.githubusercontent.com/assets/23370942/22624095/47278b0c-eb26-11e6-801e-ff6507a97975.png)

**Comment by Growlith1223** [comment]
lmao wasn't expecting it to be that bad

**Comment by ProfHugo** [comment]
I was wrong about one thing, and found out about it the hard way... since it's an ambient spawn, it keeps spawning without limit if you stay in the area, and...

IT'S A FRAMERAPE
![2017-02-04_23 26 34](https://cloud.githubusercontent.com/assets/23370942/22624452/7e0a4686-eb31-11e6-85c2-1042d048510d.png)

Note: LUL reverted 954ced8 so spells are showing nicely

**Comment by EPIICTHUNDERCAT** [comment]
wow...

**Comment by Valchap** [comment]
More dryads spawn each time you load the chunks. I don't know how to do it but spawning them when creating the chunks would solve the problem.

**Comment by Not-February** [comment]
I made a creative superflat world to test something completely different and within minutes the surrounding chunks were FILLED with dryads. I think I almost crashed my game using the /kill command(which didn't help much for the record), lol.

**Comment by Growlith1223** [comment]
you can blame Hypothermia for pestering me about releasing an update so early.

**Comment by Growlith1223** [comment]
fixed!
