### ISSUE TITLE
[1.10.2][1.5.0-17]Acacia planks crafting altar texture is odd

### ISSUE THREAD

**Issue by Not-February** [Growlith1223/ArsMagica2#176]
http://i.imgur.com/vMCJAfQ.png

It looks like a placeholder/missing texture, one of the two.

Just a heads up in case you were not already aware of it!

**Comment by Valchap** [comment]
Not just acacia but all blocks. 
If it is the same issue as #71 you can close your issue and comment in the other.

**Comment by Not-February** [comment]
Odd. Could've sworn that I used stone brick earlier today and it didn't happen with _that,_ but I'll do some more testing based on that issue you linked.

EDIT: Never mind, you're right - it's happening with jungle planks too.
