### ISSUE TITLE
Fresh Github Build (Post 18d3d65): Ayy Affinity Fix broke NPC spellcasting

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#179]
After 18d3d65, lightmage crashes the game as the game went bananas trying to get the spell manacost and altering it based on affinity when the NPC tries to cast a spell. I guess just putting a player check or something regarding NPCs using spells would be good enough (I bet bosses are also broken because of this)

A Crashlog (world can't be loaded anymore unless reverted): http://pastebin.com/hW8P9K4b

I guess it's pretty obvious what happened...

**Comment by Growlith1223** [comment]
good catch, lol
