### ISSUE TITLE
Frem Github Build: Arcane Affinity Not Reducing Manacost (Small Typo in Code)

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#180]
getAffinityDepth returns a float (?) between 0 and 1 for how deep the player affinity is, not 0-100, so this
```
if (pAffinity.getAffinityDepth(Affinity.ARCANE) > 50) {
	float reduction = (float) (1 - (0.5 * pAffinity.getAffinityDepth(Affinity.ARCANE)));
	cost *= reduction;
}
```

Will never run since getAffinityDepth cannot be more than 1, so I guess it should be 0.5 instead of 50

Note: This is getAffinityDepth:

```
public double getAffinityDepth(Affinity aff) {
	return DataSyncExtension.For(player).get(DataDefinitions.AFFINITY_DATA).get(aff) / MAX_DEPTH;
}
```
Where MAX_DEPTH is 100f

**Comment by Growlith1223** [comment]
good catch, im fixing like 3 things at once here so excuse any derps like this

**Comment by ProfHugo** [comment]
don't rush it mate, keep up the good work!
