### ISSUE TITLE
[1.5.0-17] heavy lag after placing obelisks

### ISSUE THREAD

**Issue by Andvee** [Growlith1223/ArsMagica2#182]
No crash log using using forge-12.18.3.2215

After placing an obelisk in the world I experienced heavy lag. Lag goes away after leaving the area of the obelisk. I placed the obelisk somewhere the lag wouldn't effect me before using it, and after fueling it realized that the animated texture was moving appreciably faster than older versions.

**Comment by Ajores** [comment]
Regarding this issue, my friends and I on our personal modpack have discovered major lag issues with Ars Magica 2 blocks when placed near or on chunk borders. Heaven forbid you place one of the blocks near a corner. Blocks that we've tested: Obelisk, Inscription Table, Crafting Altar, Lectern, Essence Infuser, and all have the same lag issues when placed near a chunk border/corner. Occulus, however, proved to be safe. Hope this helps debug this issue...

**Comment by Ajores** [comment]
Just to add on, it seems that multiple ars magica blocks have this issue.

**Comment by xenxero1** [comment]
This is known for the most part. I believe Growlith mentioned a potential fix either already completed, or in the works for the next release.

**Comment by TheIcyOne** [comment]
Just to confirm, you are talking about FPS drops? If this is the case, they will be fixed by  #245, but this may not make it into the next release.

**Comment by Ajores** [comment]
Yes it is a gigantic FPS drop. Looking forward to the next update in hopes that it will be fixed.

**Comment by Growlith1223** [comment]
this has been fixed. and will be in the next version
