### ISSUE TITLE
Can't start the mod, HashMap issue

### ISSUE THREAD

**Issue by PokeMaserJ** [Growlith1223/ArsMagica2#19]
I tried to start the mod, and I crashed trying to make the book 
http://paste.feed-the-beast.com/view/af31cc5a
I should mention, this is in Single Player

**Comment by Growlith1223** [comment]
have you tested without other mods?

**Comment by MrGraphic** [comment]
I saw this before, happens when you use modded item frames instead of vanilla one.

**Comment by Growlith1223** [comment]
I had a feeling it was going to be that lol, i'll see what i can do about it

**Comment by PokeMaserJ** [comment]
ugh. Just tried with just AM2. Works fine... well that's going to be annoying... *sigh*

**Comment by Growlith1223** [comment]
if you can tell me what mod exactly is causing the corruption, i can probably get it fixed

**Comment by PokeMaserJ** [comment]
I was using Vanilla Item frames though. Also, I'm not going to be able to respond for a while. I'll try adding mods slowly when I can get back

**Comment by Growlith1223** [comment]
that's fine, but once you know what mod it is that causes the crash, i might be able to fix it still lol

**Comment by PokeMaserJ** [comment]
I think I might of figured it out. Either The One Probe, or topaddons which is an addon for The One Probe. If you don't know what The One Probe is, it's an alternative to WAILA.

**Comment by Growlith1223** [comment]
i'll see what i can do about it, thanks!

**Comment by PokeMaserJ** [comment]
If I had to guess as to what is going on, one of the mods is like "What is this item frame doing?! Well I don't know how to handle this rendering, so I'll crash" Just guessing as the crash is caused by the Book getting the Etherium / essence absorbed into it.

**Comment by Growlith1223** [comment]
by chance were you holding the probe when you were making the book? lmao

**Comment by PokeMaserJ** [comment]
I had the config set to not need the probe at all.

**Comment by MrGraphic** [comment]
Uh oh... did some in depth testing in non dev enviroment
https://gist.github.com/MrGraphic/5c293c7ddad58d50bcf7be17d214297f
All you need to have is a book in a frame, no even need to point at frame - so TheOneProbe's tooltip stays hidden.
Funny thing is that it may not fire imediatelly. That's probably why I did not crashed form me - not counting modded frames case.

**Comment by Growlith1223** [comment]
this has been fixed
