### ISSUE TITLE
[1.5.0-17b] mana batteries do not get etherium from etherium sources

### ISSUE THREAD

**Issue by N7shadow2000** [Growlith1223/ArsMagica2#190]
If you pair a etherium source (like a obelisk) and pair it with a mana batterie the etherium does not get transferred to the mana batterieso that the amount of etherium inside the mana batterie remains 0.

**Comment by Growlith1223** [comment]
slap a lever next to it and turn it on

**Comment by N7shadow2000** [comment]
thanks now it works.

**Comment by Growlith1223** [comment]
no problem!

**Comment by xenxero1** [comment]
Quick question on this,  Should a crafting altar accept directly from an obelisk, when there is an etherium conduit near them?  Can't seem to link them, and I doubt the lever solution works here. Or do I need a mana battery to link it as well?

**Comment by Growlith1223** [comment]
needs a mana battery until i get around to fixing the link between an obelisk and a crafting altar
