### ISSUE TITLE
crash rendering blocks when breaking some blocks

### ISSUE THREAD

**Issue by 0Navis0** [Growlith1223/ArsMagica2#197]
I tried to break a celestial prism, but Minecraft didn't agree. I suspect Optifine to cause the issue. http://pastebin.com/VQF2gaL8

**Comment by 0Navis0** [comment]
I update this issue for telling it happens with some other blocks of the mod like the obelisk and the black aurem.

**Comment by xenxero1** [comment]
Try breaking a fully upgraded inscription table. Just a hunch. What release are you using? (yes I know its in the pastebin, but having it in the title or OP can make Identifying the issue easier)

**Comment by 0Navis0** [comment]
I use the last 1.10.2 version, and the bug doesn't occur with the inscription table. It seems to occur only with blocks which have complex shape and render.

**Comment by xenxero1** [comment]
Odd, I thought the inscription table had those properties too.

**Comment by ProfHugo** [comment]
Do you by any chance have shaders on?

**Comment by 0Navis0** [comment]
Of course, I use Optifine. The bug occurs only when Optifine is present.

**Comment by ProfHugo** [comment]
does it also crash without shaders and/or optifine?

**Comment by 0Navis0** [comment]
It crashes only when Optifine is present, with or without shaders.
