### ISSUE TITLE
[AM2 1.5.0-6] Destroying inscription table does not remove tileentity

### ISSUE THREAD

**Issue by MrGraphic** [Growlith1223/ArsMagica2#21]
...witch causes issues
https://gist.github.com/MrGraphic/db5320e69fcc30bb5d2e3f8ab10664f4
or
https://gist.github.com/MrGraphic/2a21a33a935a530729a52610d45211c0

**Comment by Growlith1223** [comment]
i've fixed it in a stupid way but im not going to post the fix as i know i can do a better fix xD gimme a few mins

**Comment by MrGraphic** [comment]
Hehe, no rush :)

**Comment by Growlith1223** [comment]
fixed!
