### ISSUE TITLE
crash on latest arsmagica build for 1.10.2 server

### ISSUE THREAD

**Issue by IronworksProductions** [Growlith1223/ArsMagica2#215]
Hey i am testing this mod on a local server before adding it to my other one and it is crashing after starting the server.

crashlog:
https://hastebin.com/owamobewih.pas

--

NN

**Comment by Growlith1223** [comment]
your first problem is you're using v15. current is 17b.

**Comment by IronworksProductions** [comment]
odd i tried that first and it crashed i will try it again

**Comment by IronworksProductions** [comment]
here is the crash from 17b:https://hastebin.com/cikukebowi.pas

**Comment by IronworksProductions** [comment]
I figured it out i was using forge version 1.10.2 2202 and that was crashing
