### ISSUE TITLE
Looking Into Occulus Before Gaining First magic Level

### ISSUE THREAD

**Issue by TheSaltyPug** [Growlith1223/ArsMagica2#22]
in the latest version, ArsMagica2_1.5.0-6, players can craft an occulus and and use it before they make the arcane compendium to unlock their magic powers.

**Comment by Growlith1223** [comment]
probably a good idea to prevent it then lol, thanks for letting me know! man, so many bugs lately lol

**Comment by TheSaltyPug** [comment]
Yeeeeep. Also, spells crafted in creative mode have no sounds for me. Haven't crafted a spell in survival yet.

**Comment by Growlith1223** [comment]
spells don't have sound at all right now they are disabled atm

**Comment by Growlith1223** [comment]
fixed!

**Comment by Zieg777** [comment]
Can we reopen this one? I cant seem to look in the occulus anymore. I've made multiple compendiums now. I'm level 40, but I cant seem to see levels, burnout, mana, or in the occulus
