### ISSUE TITLE
[1.5.0-17b] Crafting Altar Texture Missing Again

### ISSUE THREAD

**Issue by RickArendall** [Growlith1223/ArsMagica2#221]
Using forge 2185 and the latest AM2 version on curse, the crafting altar has a missing texture glitch when inserted into the structure, exactly as in the old issue #71, including the fact that it only occurs when the altar is open north-south.

I am using a GTX 1070 graphics card, holding back one driver release behind latest due to the latest drivers issues with Minecraft loading.

**Comment by Growlith1223** [comment]
it's not missing again because the fix wasn't added in version 17b.

**Comment by RickArendall** [comment]
Understood. Sorry for wasting your time with my misunderstanding.

**Comment by Growlith1223** [comment]
no worries!
