### ISSUE TITLE
[1.5.0-17b] Spellbook Next/Prev Keys Slow

### ISSUE THREAD

**Issue by RickArendall** [Growlith1223/ArsMagica2#222]
Using forge 2185 and the latest curse release, the spellbook next/previous keybinds work but are incredibly slow and non-responsive to the point of being nearly useless, especially in a combat situation.

**Comment by xenxero1** [comment]
Would you mind posting what mods your client is using?

**Comment by RickArendall** [comment]
I have the following jars in my mods folder as of the issue:
-ActuallyAdditions-1.10.2-r98
-AkashicTome-1.0-5
-ArsMagica2-1.10.2-1.5.0-17b
-AutoRegLib-1.0-2
-Bagginses-1.10.2-3.0.4g
-Baubles-1.10.2-1.3.9
-BloodMagic-1.9.4-2.1.0-69
-Bookshelf-1.10.2-1.4.3.338
-Botania r1.9-340
-chiselsandbits-12.11
-CodeChickenCore-1.10.2-2.4.0.101-universal
-CodeChickenLib-1.10.2-2.5.2.198-universal
-DarkUtilities-1.10.2-1.1.6.105
-EnderStorage-1.10.2-2.2.0.96-universal
-FastLeafDecay-v11
-Guide-API-1.10.2-2.0.2-45
-ImmersiveEngineering-0.10-55
-inventorysorter-1.10.2-0.10.5+46
-IronBackpacks-1.10.2-2.2.22
-ironchest-1.10.2-7.0.11.797
-jei_1.10.2-3.14.2.401
-journeymap-1.10.2-5.4.4
-JustEnoughResources-1.10.2-0.5.8.98
-Mantle-1.10.2-1.1.4
-MCMultiPart-1.3.0-universal
-Morph-o-Tool-1.0-12
-OpenComputers-MC1.10.2-1.6.1.6
-Psi-r1.0-42
-Quark-r1.1-70
-Railcraft_1.10.2-10.0.1
-SuperCircuitMaker-1.0.4
-TConstruct-1.10.2-2.6.1
-Totemic-1.9.4-0.7.9.1
-Waila-1.7.0-B3_1.9.4
-WailaHarvestability-mc1.10.2-1.1.9
-Wawla-1.10.2-2.3.1.213

Sorry for not including a mod list to begin with. I may try updating totemic as the version I have was meant for 1.9.4, but I used it because the 1.10.2 version at the time I downloaded was an alpha and the author's page said that the 1.9.4 version should work fine.

**Comment by xenxero1** [comment]
Having no experience in coding, I'm wondering if there is a keybind conflict, or if certain mods are trying to check for key-presses. Having to run through a bunch of checks before resolving could be a possible cause of issue. In the mean time, I prefer to sneak-scroll to switch my spells.

I could see Quark, Chisel&Bits, and a few other mods that add a lot of client-side functions/keybinds could be a part of the issue.

**Comment by RickArendall** [comment]
Curious that none of the other mods seem sluggish. Maybe Ars Magica just "drew the short straw" so to speak on priority if that's the case? I might do a test instance with only Ars Magica when I have time later.

**Comment by xenxero1** [comment]
To be fair, I'm just a tester and am not familiar with the innerworkings, so take everything I say with a grain of salt. I mostly post those observations to try and help anyone fixing the code, by giving them a possible place to start. :)

**Comment by xenxero1** [comment]
I've retested on the Spinycraft V2  Pack - 1.2.0.

Unable to reproduce. leads me to believe this is an issue with another mod, if not the number of mods using keybinds.

**Comment by RickArendall** [comment]
The issue was on my end and I found a fix. For some reason the launcher (I'm using the newest) did not properly update lwjgl and Minecraft was using an old version instead of the newest (which was downloaded also, but in a separate folder unused for some reason).

Deleting the folders for the old lwjgl versions forced Minecraft to use the proper version and completely fixed the non-responsiveness.
