### ISSUE TITLE
Winter Guardian unable to be summoned

### ISSUE THREAD

**Issue by xenxero1** [Growlith1223/ArsMagica2#224]
I'm unsure if he was disabled due to the old game-breaking bug he had, but attempting to summon him as the Arcane Compendium outlined does not appear to work. I have 3 snow golems close to a gold inlay. Inside the gold inlay are 2 pieces of ice, topped off by a Blue-Topaz block. The entire setup is located in the mountains, High up on the natural snowcaps.

I vaguely remember something about the changes in meta blocks causing an issue here, but I'm unable to find any followup. 

Current Release: Ars Magica 2 1.5.0-17b

Spinycraft V2 -1.2.0

Minecraft 1.10.2

**Comment by ProfHugo** [comment]
"Due to the removal of metadata values, the Lightning Guardian and the Ice Guardian now requires a special block in place of the top one." READ THE README

**Comment by xenxero1** [comment]
I've read that. But it had no mention of WHAT block to use.

**Comment by ProfHugo** [comment]
Oh, in the creative menu, there are 2 blocks with missing texture (forgot the name), but yeah, it's there.

**Comment by xenxero1** [comment]
I'm guessing there not obtainable in survival? Although at that point I probably shouldn't feel bad throwing away the topaz and spawning in the blocks.

**Comment by camilla-ett** [comment]
Fix #229
