### ISSUE TITLE
[Ars Magica 2 1.5.0-17b] Obelisk still cannot connect to mana batteries or Crafting Altar.

### ISSUE THREAD

**Issue by xenxero1** [Growlith1223/ArsMagica2#225]
https://github.com/Growlith1223/ArsMagica2/issues/154

I'm still getting this bug on the -17b release from Curse-Forge. I can fuel an essence refiner and a calefactor no problem. It says it pairs with a mana battery, yet the battery doesn't accept anything. I've also tried linking it directly to a crafting altar, which throws an error saying "No path found."

Retested again with an etherium conduit present and in different combinations of linkings. No success aside from calefactor and essence refiner. I've only tested with a base obelisk, with wizard chalk and stone pillar upgrades, and a default non-upgraded Black Aurem. Have not tested with Celestial Prism +- upgrades, or Black Aurem + upgrades.

**Comment by N7shadow2000** [comment]
Put a lever on the mana battery then it should charge

**Comment by xenxero1** [comment]
As someone who's played with Ars magica since its birth, I have never facepalmed so hard.
I will test this as soon as I get home, and post some followup as necessary. Closing if applicable.

**Comment by renadi** [comment]
I'd like to ask a question, as this seems to be a very common issue people
have, is there any good reason to require redstone to charge the mana
battery?

I don't see the benefit and it frustrates newbies, and veterans alike.

**Comment by xenxero1** [comment]
I could see justification to have redstone interactions, like powering it to disable charging. But not so much requiring a signal to use its only major function :)

**Comment by N7shadow2000** [comment]
Being able to activate and deactivate the charging of mana batterys alows you to controll where your etherium goes at the moment. This could be useful in complex systems

**Comment by xenxero1** [comment]
Using the lever did in fact, work. After linking the battery to the altar, the obelisk was then able to link to the altar as well.

**Comment by InjuredWolf** [comment]
Maybe the redstone setting should be inverted? Redstone on disables the battery's ability to accept charge? Just a suggestion.

**Comment by xenxero1** [comment]
This is what I was trying to say. Like have it function by default.

**Comment by STS15** [comment]
Put Magitech glasses on to connect them.  I am using the same version on my modpack(17b), and It wasn't working.  I can confirm that it now works with the glasses on.

**Comment by xenxero1** [comment]
I was wearing magitech headgear as well. It still would not connect without a red-stoned battery connected first.
