### ISSUE TITLE
Am2 armor takes durability damage from all damage sources

### ISSUE THREAD

**Issue by xenxero1** [Growlith1223/ArsMagica2#228]
AM2 -17b release for 1.10.2

An expansion of the issue found here: https://github.com/Growlith1223/ArsMagica2/issues/195

Upon further testing, I can confirm this is an issue with Am2 and not blood magic. Everything from being on fire, to taking wither/poison damage, to being in lava or even drowning; will cause damage to the armor. This only occurs with Am2 armor, and not with any other mod's armor.

While not usually an issue due to the regen, Catching fire a couple of times is enough to break starting mage armor.

**Comment by TheIcyOne** [comment]
This has been part of AM2 since at least 1.7, but I think it used to actually provide bonuses against those damage types.
