### ISSUE TITLE
Server crash caused by player casting a spell on another player.

### ISSUE THREAD

**Issue by xenxero1** [Growlith1223/ArsMagica2#230]
Sadly I was unable to retrieve the crash log. Me and 3 other players were on our server. One casts Projectile || Fire Damage at me. I was in survival. Instead of rendering damage when it landed, the server crashed immediately, kicking everyone off. Server started up no problem. Both me and the other player were holding Arcane Spellbooks, While I had 100% Earth affinity, and they had ~13.6% Fire affinity. 

Tested on Spinycraft V2 1.2.0

AM2 build -17b

**Comment by Growlith1223** [comment]
i can't really do very much without a crash log, but i'll see if i can do anything.

**Comment by xenxero1** [comment]
I will look in my files and see if it cached one somewhere.  The console cleared too quickly is what I really meant.

**Comment by xenxero1** [comment]
I believe this was not an Ars Magica issue. Same player shot me with a hunters gun from RandomThings, using neutral bullets. Instantly crashing the server again.

It should be noted that I was also holding the Arcane Spellbook at the time. Which I will be submitting another report on why this could be relevant.
