### ISSUE TITLE
Everstone block crashes server and corrupts world

### ISSUE THREAD

**Issue by honswlos** [Growlith1223/ArsMagica2#239]
I placed one block of Everstone, and I was trying to apply the stone block to it, but it wasn't working.  I was going to try a dirt block next just to test it, and I might have accidentally clicked on it with another everstone block.  I tried to remove the block with tools and with dig magic, and it would crash the server every time.  I also tried just being around it without trying to remove it, and the server crashed after a minute or so.  I had no choice but to roll back to a previous save of the world.

Here's the client crash dump:
http://pastebin.com/ZsmSQRBz

And here's the server crash dump:
http://pastebin.com/gXTQTVBd

Minecraft: 1.10.2
Forge: 1.10.2-12.18.3.2185-universal
ArsMagica2-1.10.2-1.5.0-17b
Not using OptiFine

**Comment by TheIcyOne** [comment]
Issue occurs in the getBlockHardness method of the Everstone block.
