### ISSUE TITLE
Crash when rendering a particle name "arsmagica2.Shockwave"

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#25]
Game throws array index out of bounds when trying to render this particle. Using /summon to render this particle or using anything that generates it would cause this crash. Should be noted that the Earth Guardian generates this particle with its slam attack.

crash log when summoning:
http://pastebin.com/MYMfBfh8

**Comment by Growlith1223** [comment]
fixed!
