### ISSUE TITLE
Mana Draining Well does not produce Neutral Essence and Instantly breaks

### ISSUE THREAD

**Issue by xenxero1** [Growlith1223/ArsMagica2#259]
With the full multiblock constructed as depicted in the book, nothing happens while interacting with the center block. Additionally, Sneak Right-clicking the block instantly destroys it.

**Comment by TheIcyOne** [comment]
I can't reproduce this in my world, can you post a screenshot of your setup?

**Comment by xenxero1** [comment]
After further testing it no longer seems to break (for now. it happened the one time under a weird right-click-sneak-while-holding-jump scenario). I will post a screenshot of my setup in about 9 hours.

**Comment by xenxero1** [comment]
![image](https://cloud.githubusercontent.com/assets/14264597/23535109/4909bf08-ff8a-11e6-9b27-5e12131241fa.png)
 Here is the screenshot as requested

**Comment by TheIcyOne** [comment]
The pillars are in the wrong place, they should be one block out from the magic walls, in the middle of the edge of the structure.

**Comment by xenxero1** [comment]
well I feel silly now.  Book did not really display it clearly to be fair. I'l test it tonight after modifying the structure and close if applicable.
 Just to be clear, itl look the same shape-wise to upgraded obelisks and the like?

**Comment by TheIcyOne** [comment]
Not quite, the pillars are in line with the well, rather than on the diagonal.

**Comment by xenxero1** [comment]
So the structure will be Oblong?
 Or more rotated-points?

**Comment by xenxero1** [comment]
Issue was a mistake on my part, of not building the structure correctly. Closing.
