### ISSUE TITLE
Three modifier limit can be worked around [ArsMagica2_1.5.0-6]

### ISSUE THREAD

**Issue by emeralis00** [Growlith1223/ArsMagica2#26]
When writing a spell, up to 6 copies of the same modifier can be put into the spell.

Steps to reproduce:
1. Put a shape in the Shape Group
2. put three modifiers of the same type in the Spell grammar
3. put a shape in the Spell Grammar after the 3x modifiers
4. put the same modifier into the Shape Group up to three times
(5. finish up a spell)

In this way, for example, it is possible to get duration x6 onto a spell.

**Comment by Growlith1223** [comment]
fixed!
