### ISSUE TITLE
Shield Overload Silver Component will not unlock

### ISSUE THREAD

**Issue by xenxero1** [Growlith1223/ArsMagica2#269]
Shield Overload is depicted in the UnlocksManager file as a silver component unlocked through casting Mana Shield + Mana Drain. Ive crafted the spell and cast it successfully, but no silver component seems to have been unlocked.

AM2: -17b for 1.10.2

Spinycraft V2 Modpack 1.2.1

**Comment by Daomephsta** [comment]
I have just attempted to reproduce this issue in a dev environment and failed. I was using a Self-Mana Shield-Mana Drain spell, upon casting it I unlocked Shield Overload.

Edit: Testing with a Projectile-Mana Shield-Mana Drain spell in v1.10.2-1.5.0-17b has also failed to reproduce this issue.

**Comment by xenxero1** [comment]
Out of curiosity, where exactly would the component be displayed? I may have unlocked it, but just hadn't seen it in the occulus.

**Comment by Daomephsta** [comment]
@xenxero1 
Shield Overload is in the rightmost tab of the Occulus, near the bottom left.

**Comment by xenxero1** [comment]
Terribly sorry, found it now. Although the Arcane compendium seems to have no information on it, Il log that as a secondary defect. Appreciate the help!
