### ISSUE TITLE
Crash with two active chrono anchors [ArsMagica2_1.5.0-6]

### ISSUE THREAD

**Issue by emeralis00** [Growlith1223/ArsMagica2#27]
Using forge version 2119 for 1.10.2

It is possible to cause a reliable crash upon world reload when exiting the world with two active chrono anchor spells.
Steps to reproduce:
1. Make a spell with the following
   Shape group: Zone, Duration x3
   Spell grammar: Self, Chrono Anchor
2. Cast this spell twice
3. Exit the world
4. Re-enter the world (Crash Step)

Re-entering the world a second time allows the world to load completely with no crash. To cause crash again, simply cast the spell twice and exit the world.

Crash Report: http://pastebin.com/raw/H1D0GSQb

**Comment by Growlith1223** [comment]
fixed!
