### ISSUE TITLE
Config generating with file path as name

### ISSUE THREAD

**Issue by primetoxinz** [Growlith1223/ArsMagica2#28]
![gscreenshot_2016-11-10-185951](https://cloud.githubusercontent.com/assets/4721642/20199358/ed72ea6c-a777-11e6-842e-f46201875644.png)
Instead of generating in the intended directory the config generates with the path as the full name of the file.
This may be due to being on linux, but is a problem nonetheless

**Comment by Growlith1223** [comment]
hopefully fixed... lol
