### ISSUE TITLE
R-8 - Crashes server on load

### ISSUE THREAD

**Issue by aridhol** [Growlith1223/ArsMagica2#29]
[crash-2016-11-11_12.41.16-server.txt](https://github.com/Growlith1223/ArsMagica2/files/586524/crash-2016-11-11_12.41.16-server.txt)

Logs attached, I'm not sure what all is causing it.. It was working fine with R-6

**Comment by aridhol** [comment]
Looking over the logs, it looks like it might be calling for some single player assets on the server? I'm sure you know better than I do, but that is what I am seeing

**Comment by pirone2** [comment]
Happens here too on the 1.5.0-8 release...
Here's a log:
[2016-11-11-7.txt](https://github.com/Growlith1223/ArsMagica2/files/586616/2016-11-11-7.txt)
Please, release a fix as soon as possible.

**Comment by Growlith1223** [comment]
new version will be up in a few!

**Comment by Growlith1223** [comment]
fixed!
