### ISSUE TITLE
WitchWood forest is not registered as a biome

### ISSUE THREAD

**Issue by primetoxinz** [Growlith1223/ArsMagica2#30]
don't know if this is intentional, but the biome is never registered, so it can't generate

**Comment by Growlith1223** [comment]
is it set to true in the configs to enable the biome?

**Comment by primetoxinz** [comment]
Yes

**Comment by whichonespink44** [comment]
Just tried adding RTG support for the Witchwood Forest, and I can confirm that it's not being registered even if set to true in the configs.

**Comment by Growlith1223** [comment]
this has been fixed!
