### ISSUE TITLE
[Question] Do Am2 light blocks spawn as tile-entities?

### ISSUE THREAD

**Issue by xenxero1** [Growlith1223/ArsMagica2#303]
I remember someone telling me this once, when they asked us to not use Light spells on their server. I know there were several glitches involving this that have since been resolved but the question remains for me.

I ask mainly because having the Light Step armor enhancement seems self-dooming -- destroying your computer with tile-entities.

**Comment by TheIcyOne** [comment]
They have no reason to, so almost certainly yes ;) I'll have a look when I get to a PC.

**Comment by TheIcyOne** [comment]
Nevermind, no tile entities involved.
