### ISSUE TITLE
Crystal markers don't save their facing value.

### ISSUE THREAD

**Issue by Mowmaster** [Growlith1223/ArsMagica2#306]
Crystal Markers don't save their facing value on entering the chunk or on world reloading. I have been told you can save the facing values in the TE. personally i don't know how to do this but if you made each crystal marker a seperate block then you could store the facing in the block class like i do in my mod: [Block class with Facing saved](https://github.com/Mowmaster/Dust/blob/master/src/main/java/com/mowmaster/dust/blocks/BlockCrystal.java)

**Comment by Growlith1223** [comment]
Crystal Markers?

**Comment by Growlith1223** [comment]
Found what you mean, Import and Export crystals, Will be fixed in next version
