### ISSUE TITLE
Ender Affinity's Night Vision and Anti-Enderman Agression doesn't trigger

### ISSUE THREAD

**Issue by SpicyScallionSoup** [Growlith1223/ArsMagica2#309]
As stated above, the following effects does not seem to trigger. I'm playing on 1.10.2 version on Nuts and Bolts: Torqued, with the latest forge, ArsMagica2-1.10.2-1.5.0-18 version. I hope I supported enough info to help you tackle the issue.

Side note: Ender Affinity is at and well over 100%, locked, debuffs triggered correctly on their respective affinity range, now of course grown past, but worked as intended.

**Comment by TheIcyOne** [comment]
Not sure we even have them enabled in the code ATM.

**Comment by xenxero1** [comment]
Night vision works for me on the -17b version. Or rather a player on my server. Haven't tested the enderman aversion however.

**Comment by SpicyScallionSoup** [comment]
Update: Night Vision had a key all along (I'm an idiot, sorry guys), dislocation works just fine, and endermen aversion might be countered by hardcore mobs mod that the pack has. Sorry for wasting your time I guess :/

**Comment by TheIcyOne** [comment]
Don't worry, you've helped. I can now say "working as intended" when somebody mentions it not working.
