### ISSUE TITLE
etherium storage not working ?

### ISSUE THREAD

**Issue by sasuke0614** [Growlith1223/ArsMagica2#319]
Hi, first thank you so mush, you who are working on the update of this amazing mod.
But i have a problem about the etherium storage. I have all the required components( obelisk, mana battery etc) i have the ''paring sucessfull'' message, but the mana battery doesn't seem to store anything. Did something changed ?

**Comment by TheIcyOne** [comment]
Apply a redstone signal to the battery.

**Comment by Growlith1223** [comment]
did your problem get solved? should just be what icy said, apply a redstone signal to the mana battery.

**Comment by sasuke0614** [comment]
Yes, it did solve the problem, i just didn't read the book right ^^
Thanks a lot for the answer !
