### ISSUE TITLE
Mana Battery does not maintain mana when broken

### ISSUE THREAD

**Issue by Yowesephth** [Growlith1223/ArsMagica2#32]
When broken, the mana battery won't remember how much mana it has. the NBT takes remember that it had neutral etherium, but not much much, showing 0, and being placed makes an empty battery.

**Comment by TheIcyOne** [comment]
@jjtParadox had a fix for this waiting on Mithion's repo, didn't get merged though.

**Comment by Growlith1223** [comment]
thanks for telling me about that, i never thought to look at the PRs on the original thread, i was going to create the fix lol this just makes it easier

**Comment by Growlith1223** [comment]
fixed!
