### ISSUE TITLE
Please do not use mob damage for non EntityLivingBase entities

### ISSUE THREAD

**Issue by rafradek** [Growlith1223/ArsMagica2#321]
I my mod I check if the attack is a standard melee attack by checking if the damage type is "mob" or "player". But it looks like your mod does label attacks from non-EntityLivingBase entities as such, which is stupid since a mob is considered a living entity.

**Comment by xenxero1** [comment]
I think (not sure, so take it witha  grian of salt) that the damage type is shared between players and mobs with AM2. The damage method of magic scales for both mob and player when changed in the config file, so I do believe they share the same methods.  I think a change like this would require an entire rework of the code. 

tl;dr Magic is weird, I wouldn't hold my breath until all the current bugs and features are sorted out.

**Comment by rafradek** [comment]
Actually this does not need to change, I was simply upset that I had to add extra checks. I did not expect that they are actually needed.
