### ISSUE TITLE
[Request] Biome ID config

### ISSUE THREAD

**Issue by ghost** [Growlith1223/ArsMagica2#325]
I'm getting a conflicts and I need to reassign IDs.

**Comment by TheIcyOne** [comment]
# Sets the biome ID that Witchwood Forest will use. Default: -1 (automatic))
    I:WitchwoodForestBiomeID=116

**Comment by TheIcyOne** [comment]
From am2.cfg

**Comment by ghost** [comment]
My eyes went straight past it repeatedly. Thanks.
