### ISSUE TITLE
Feather touch turns Granite/Andesite/Diorite into Smooth Stone

### ISSUE THREAD

**Issue by Zieg777** [Growlith1223/ArsMagica2#33]
So Feather touch now works on ores and stone, but it turns the other stone variants into smooth stone as well.

**Comment by Growlith1223** [comment]
ugh... fixed XD

**Comment by Zieg777** [comment]
:D thanks!

**Comment by Zieg777** [comment]
Figured I'd also mention it here. It does the same with the various tinkers slime dirts. Magma slime dirt turns to regular, etc. Same with the slime blocks
