### ISSUE TITLE
[1.5.0-18] Draining Well not transmitting power when paired

### ISSUE THREAD

**Issue by XFRGod** [Growlith1223/ArsMagica2#342]

**Comment by xenxero1** [comment]
If you're trying to store it in a battery, make sure you are applying a redstone signal (down-position lever) to the battery. If that still doesn't work, make sure the structure is 100% correct. I made both mistake initially.

**Comment by XFRGod** [comment]
Ever since I restarted the game and the local server it seems to be working but when I place it at first it doesn't want to behave.
Well, a reset solved it.

**Comment by Growlith1223** [comment]
Might be a sync issue, i'll look into it
