### ISSUE TITLE
Spawning bosses removes whole stack of items instead of one item.

### ISSUE THREAD

**Issue by DreenDex** [Growlith1223/ArsMagica2#346]
By dropping 16 **Air Essense** i got only one boss.
![image](https://cloud.githubusercontent.com/assets/6661231/26459659/defbc79a-417f-11e7-931c-0026a51f000f.png)

**Comment by Growlith1223** [comment]
This is the same thing that happened with 1.7.10, just letting you know, it's not a bug of any kind
