### ISSUE TITLE
Error updating to 1.5.0-8  

### ISSUE THREAD

**Issue by Frinckles** [Growlith1223/ArsMagica2#35]
Booting up server with new update. Crashes and throws the following error

Server Crash Log: http://pastebin.com/iCsLFDKi

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/**EntityPlayerSP** 

I'll pretend to know what I'm talking about from my little experience and assume it's because you're messing with stuff like this in the latest update. 

> //else if (transformedName.equalsIgnoreCase("net.minecraft.client.entity.**EntityPlayerSP**"))
>-		//	return alterEntityPlayerSP(basicClass, !Preloader.isDevEnvironment);

I'm assuming it has to do with that class not existing, but I'm probably wrong, I'm a hack who likes visual programming so I'm terrible with this stuff. I'll see if there's a newer version of Forge that it will work with. 

**Forge Version:** Forge-1.10.2-12.18.2.2123-universal.jar

Let me know what you find, thanks. Oh and thanks for reviving AM2.

**Comment by Frinckles** [comment]
Tried with newer **Forge Version:** forge-1.10.2-12.18.2.2125-universal.jar

Still tossing the error related to net/minecraft/client/entity/EntityPlayerSP.

**Comment by Growlith1223** [comment]
not sure what's up with the releases but there's a .9 update that fixes said issue and no, it's not that line commented out

**Comment by Frinckles** [comment]
1.5.0-9?  

Sorry.

**Comment by Growlith1223** [comment]
yep, no problem! for some reason it said from Feb 11 lmao, i redone the release

**Comment by Frinckles** [comment]
Dope. One more question, just because one day I'll get back into programming: What was the cause of the error between 8 -> 9 ? It had nothing to do with EntityPlayerSP?

**Comment by Growlith1223** [comment]
https://github.com/Growlith1223/ArsMagica2/commit/04e9adee8e89e2119ab2179aecb19e209866876f

i used the local player on the server by accident lol

**Comment by Growlith1223** [comment]
in depth:
i used the Mc.getMinecraft.getPlayer which gets the player of the client, which is an EntityPlayerSP object, which is only available on the client side, hence the crash on the server.

**Comment by Frinckles** [comment]
Word, makes sense. Thanks for the insight. I'll keep you posted on any errors I find.
