### ISSUE TITLE
Version 1.5.0-8: Air Guardian borking the game

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#37]
Anytime during the Air Guardian using its channeled spin attack the game would freeze up, causing most in-game functions to be disabled, the most prominent one being mob AI. Exiting the game would cause it to not respond. 

The game log doesn't seem to mention anything about the freeze. Also the AI of the Air Guardian appears to be deactivated until a player in survival mode attacked it.

**Comment by Builderb0y** [comment]
Having the same issue. VisualVM says that am2.bosses.ai.EntityAIHurricane.func_75253_b() is stuck in an infinite loop, or at least consuming 100% of the server thread.

**Comment by StarkRG** [comment]
This sounds like the same issue I've been having. Posted in another issue, but it turned out that wasn't the same problem.

> While I can confirm that the Air Guardian has issues it's not causing our server to crash, merely hang and not respond. This occurs immediately after the spinny-break-block move (I can hear the blocks break but don't actually see them).

> This is SMP on dedicated server. (nothing revealing in the logs)

The AM2 release is 1.5.0-11

**Comment by Saereth** [comment]
this is still occurring on -15

**Comment by Growlith1223** [comment]
there is no -15 mate, how could it happen on a non-existant version ;)

**Comment by Saereth** [comment]
sorry meant version 12, pulled the latest from here and built just to see :p

**Comment by Growlith1223** [comment]
lol it's fine, i'll be posting a new version soon though

**Comment by EPIICTHUNDERCAT** [comment]
fixed right? @Growlith1223

**Comment by StarkRG** [comment]
Can confirm, air guardian doesn't crash the server.

**Comment by EPIICTHUNDERCAT** [comment]
fixed and closed until further notice
