### ISSUE TITLE
Version 1.5.0-8: Arcane Guardian Spellcasting Crash

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#41]
It appears that when the Arcane Guardian tried to heal itself via spell-casting, it crashes the game almost immediately.

Crashlog - http://pastebin.com/neCCqZAk

**Comment by Zieg777** [comment]
And here I tried using Silence to mute him before he could cast. All to find out that bosses are immune to Silence..

The good news is it's not an instant crash each time you log in. You can slowly chip away at him one spell at a time.. I used NBTExplorer to just set his hp to 1 so I can still kill him. Not ideal, but at least the world isnt unrecoverable.

**Comment by Zieg777** [comment]
Similar Crash with fire guardian. This one it's the spell effect's entity that's crashing though.

http://pastebin.com/ETYC1CS7

**Comment by Growlith1223** [comment]
fixed!
