### ISSUE TITLE
Spell book next/prev keybinds nonfunctional

### ISSUE THREAD

**Issue by Yowesephth** [Growlith1223/ArsMagica2#47]
Tried it with a few different keys, t/g, ,/., t/y, none seemed to function.
Crouch and scrollwheel does work currently.

**Comment by aridhol** [comment]
The keybinds are supposed to be Z and X - but they don't work. This is a known bug

**Comment by valentin616** [comment]
This bug is no more #165

**Comment by Valchap** [comment]
fixed #166
