### ISSUE TITLE
Cannot replace blocks picked up by Appropriation

### ISSUE THREAD

**Issue by Zieg777** [Growlith1223/ArsMagica2#48]
I made a simple projectile>appropriate spell for moving blocks/spawners/mobs. I tested it on a wall next to me and it picked up the piece of smooth stone.

Now I cant put it down, and I cant pick up anything else.

Quick edit. I was able to hit an entity with it. This made the smooth stone block appear in their feet. Perhaps its trying to place the block in the block it hits? Does it need to target the side of the block it hits instead?

**Comment by Zieg777** [comment]
I can kinda work around it by casting it at a mage lamp. Works for mobs at least

**Comment by Growlith1223** [comment]
fixed!

**Comment by Zieg777** [comment]
Woot! no more placing blocks on mobs and placing mobs on mage lamps
