### ISSUE TITLE
[Question] - I'm very lost.

### ISSUE THREAD

**Issue by Hameggontoast** [Growlith1223/ArsMagica2#49]
I'm sure this is due to my own incompetence but can someone please tell me how to create power in this mod? Back in the day I could just click the ground with some chalk in the middle of some pillars and I'd be gucci.

**Comment by TheIcyOne** [comment]
For neutral essence, place an obelisk and give it vinteum dust or a bucket of essence as fuel. The light and dark generators can be made using rituals documented in the compendium, which I don't trust myself to explain properly here.

**Comment by Hameggontoast** [comment]
Are the other 2 craftable? My friend says he attempted the rituals but they do not work.

**Comment by TheIcyOne** [comment]
The other two are ritual-only, I don't think the rituals have been changed from those documented in the compendium entries.

**Comment by Zieg777** [comment]
Worth noting that they're not currently showing up for me in the compendium.

**Comment by Growlith1223** [comment]
the compendium thing is already being worked on, the base is there, just isn't finished yet
