### ISSUE TITLE
1.5.0-9 Chiseled stone brick recipe conflicts with extrautilities 2 polished stone recipe

### ISSUE THREAD

**Issue by Lyl4c** [Growlith1223/ArsMagica2#54]
minecraft 1.10.2
forge 12.18.2.2151
ArsMagica2_1.5.0-9
extrautils2-1.10.2-1.1.0

Title says it;  There is no way to change either recipe in either mod. Also the current recipe in the mod is redundant and not needed as vanilla minecraft has provided a way to craft the chiseled stone brick using two stone brick slabs on top of each other. [[Link](http://minecraft.gamepedia.com/Stone_Bricks#Crafting)]

**Comment by Growlith1223** [comment]
recipe has been removed, i completely forgot that Ars Magica added in a recipe for it lol
