### ISSUE TITLE
Version 1.5.0-9: Dispel does not work, at all

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#56]
Dispel not only fails to remove any potion effect from its target, it also made any potion effect last permanently...
(countdown stays at 0)

*potion effects would re-position itself in menu the second it hits 0:00

I PRESENT TO YOU: SUPERMAN HIGH ON VINTEUM SULFATE

![2016-11-22_18 32 19](https://cloud.githubusercontent.com/assets/23370942/20549571/77efdfba-b0e2-11e6-84bc-45c00cb21b71.png)

**Comment by renadi** [comment]
This is another one of those, "Could it be a feature" things.

A spell that -fixed- your current potion effects would be awesome, as long
as it had some kind of crash when you let it run out.

**Comment by ProfHugo** [comment]
Oh would that be absolutely broken

**Comment by Growlith1223** [comment]
this has been fixed!
