### ISSUE TITLE
Version 1.5.0-9: Blink is named Blind in compendium and inscription table

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#57]
For some reason, the component Blind and Blink are both named Blind in both of their menus.

1. Compendium entry
![2016-11-22_17 38 52](https://cloud.githubusercontent.com/assets/23370942/20549609/df7ddd9e-b0e2-11e6-83c3-e6f13719139e.png)

2. Table menu
![2016-11-22_17 39 05](https://cloud.githubusercontent.com/assets/23370942/20549616/f0309e38-b0e2-11e6-8880-6fdcab2046e2.png)

*Functionality is unchanged, should only need a minor text fix

**Comment by Zieg777** [comment]
Similarly, Mana Shield shows up as Mana Blast in the compendium, though the table is fine. Description still implies the shield.

**Comment by aridhol** [comment]
I noticed this also

**Comment by Growlith1223** [comment]
fixed!
