### ISSUE TITLE
Version 1.5.0-9: Disarm does not work on mobs

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#58]
Using projectile disarm does not affect zombies, skeletons and zombie pig-mans at all. Most likely to not work on other mobs as well.

*Still works on players

**Comment by Orinion** [comment]
Fixed? We could still add ProfHugo's suggestion of making disarm also drop the offhand item when combined with power or so

**Comment by Growlith1223** [comment]
as i have said, i am not working on features atm, i'd like to get certain bugs fixed before i do start working on features(that could very well break even more things), while I won't work on features ATM, i am more than happy to accept PRs for features.

**Comment by Growlith1223** [comment]
Going to close this, if you want to, make a new issue as a suggestion for your suggestion!
