### ISSUE TITLE
No animation on Mana elemental

### ISSUE THREAD

**Issue by Divineaspect** [Growlith1223/ArsMagica2#6]

**Comment by Growlith1223** [comment]
There was never an animation on the mana elemental to begin with.

**Comment by Divineaspect** [comment]
I mean it's not even rotating, raising it's arms like it did in 1.7

**Comment by MrGraphic** [comment]
It's because mobs AI has been turned off. Already fixed :).

**Comment by Growlith1223** [comment]
That was the Earth Elemental that had its AI disabled, the mana elemental doesn't have its ai disabled.

**Comment by Divineaspect** [comment]
Have determined it was something related to an emote mod.
