### ISSUE TITLE
1.5.0-9 arcane compendium's gui being dark in menu, and text title on the inlays and mana blast section

### ISSUE THREAD

**Issue by alpha8196** [Growlith1223/ArsMagica2#72]
as title
[http://imgur.com/VJaGJNL](url)

**Comment by Growlith1223** [comment]
what mods do you have on? running purely ars magica, im not getting it

**Comment by Growlith1223** [comment]
the darkness i mean, the names i know about

**Comment by alpha8196** [comment]
I'm playing a mod pack i build my self so I don't have a mod list, this is the closest thing I have
[http://imgur.com/rDdsgAT](url)
[http://imgur.com/7SdtOTq](url)

**Comment by ElvenChaos** [comment]
@alpha8196 Did you happen to cut some of the mods out of your list? I was having the dark book issue on my custom server pack, so I compared your list to mine to grab all the similar mods and put them in their own test pack. For some reason the test pack, which should have had the issue, doesn't.

Also, do you notice the issue while playing single player, or is the issue only on a server environment?

**Comment by alpha8196** [comment]
@ElvenChaos actually ,yes 
there is also WIRED:More Augs
Xaero's minimap
Zero core(which I guess you have it already)
I was in single player to test it when I noticed this

**Comment by Growlith1223** [comment]
i've released a new download, see if it doesn't happen now

**Comment by alpha8196** [comment]
@Growlith1223 yap, it solved the problem
