### ISSUE TITLE
1.5.0-11 Lectern cannot properly display inksek

### ISSUE THREAD

**Issue by alpha8196** [Growlith1223/ArsMagica2#79]
yap,its me with a not important bug again
[http://imgur.com/PkPDpmA](url)

**Comment by Growlith1223** [comment]
lmao what in the world, i'll take a look, thanks for telling me!

**Comment by Growlith1223** [comment]
could you specify what you used to make said spell

**Comment by alpha8196** [comment]
just projectile and physic damage

**Comment by Growlith1223** [comment]
if you're talking about an ink sak, those parts don't have an ink sak in the reagants

**Comment by alpha8196** [comment]
perhaps there is also color? I can't check that yet…

**Comment by alpha8196** [comment]
@Growlith1223 yap,I also have Colour

**Comment by alpha8196** [comment]
also under forge 2185

**Comment by shadow-absorber** [comment]
can confirme this is still a thing

**Comment by Growlith1223** [comment]
fixed!
