### ISSUE TITLE
Arcane Deconstructor Crash

### ISSUE THREAD

**Issue by GeorgeZn** [Growlith1223/ArsMagica2#82]
So, upon putting in the deconstructor a spell, it just really doesn't like it, and crashes the game.

[crash-2016-12-07_15.57.47-server.txt](https://github.com/Growlith1223/ArsMagica2/files/637904/crash-2016-12-07_15.57.47-server.txt)

**Comment by Growlith1223** [comment]
this'll probably be the last thing i fix for today as im a bit sick lol

**Comment by Growlith1223** [comment]
fixed!
