### ISSUE TITLE
v1.5.0-11 Flicker Habitat Crashes Server When Given Essence

### ISSUE THREAD

**Issue by Indeflab4** [Growlith1223/ArsMagica2#83]
Specifically, when given Neutral Essence from a mana battery and using the Felled Oak Flicker Focus, the server immediately crashes. There is enough time when the server restarts to disconnect the habitat from the essence network, but only about 30 seconds. 

I've tried this in a creative single player world as well, with just this mods, and the instance crashes there as well. 

Server crash report: [crash-2016-12-07_18.08.42-server.txt](https://github.com/Growlith1223/ArsMagica2/files/637987/crash-2016-12-07_18.08.42-server.txt)

**Comment by Growlith1223** [comment]
fixed!
