### ISSUE TITLE
1.5.0-11: Invisibility Null Pointer Crash + Wrong Potion Effect 

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#84]
Using self invisibility would cause a null pointer crash (http://pastebin.com/VUxX08mh)

Not only that, but when you load back in, you would have a potion effect called Agility (gives you a movespeed boost and 2 blocks jumping)

**Comment by Zieg777** [comment]
Sounds like something related to Potion ID conflicts.

**Comment by ProfHugo** [comment]
that should be the case if it's 1.7.10, but didn't mojang changed potion effects to use the modname.potion name format instead of numeral ids?

**Comment by Growlith1223** [comment]
slightly fixed.
