### ISSUE TITLE
1.5.0-11: Entangle causes mobs to be stuck in mid air, but not players

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#89]
Using entangle on any mob would cause it to be stuck in mid air if it's airborne, but if players are hit with entangle they still freefall if they're airborne.

![2016-12-09_20 00 39](https://cloud.githubusercontent.com/assets/23370942/21071085/8b2b04ea-be4a-11e6-8c72-a0742b56e773.png)

**Comment by Growlith1223** [comment]
fixed!
