### ISSUE TITLE
1.5.0-11: Reflect has no effect

### ISSUE THREAD

**Issue by ProfHugo** [Growlith1223/ArsMagica2#92]
Self-reflect does not deflect spells cast by light mages, and using projectile-reflect on a lightmage would also have no effect whatsoever

**Comment by Zieg777** [comment]
Interesting. Because magic walls now actually have the reflect property. Though I can't actually hit myself with my own projectile with it... Though I can hit myself with my own light spell if I fly fast enough.

**Comment by Growlith1223** [comment]
fixed!
