### ISSUE TITLE
Fire Guardian Crash

### ISSUE THREAD

**Issue by Sideburns180** [Growlith1223/ArsMagica2#95]
The fire guardian is causing some crashing.       Here is the report
[fire guardian crash.txt](https://github.com/Growlith1223/ArsMagica2/files/644022/fire.guardian.crash.txt)

was able to get a look at it before crashing again, it certainly is trying to cast something beforehand.

**Comment by ProfHugo** [comment]
Was it trying to cast "firestorm", only to found that it's missing since the former "firestorm" was renamed firerain?

EDIT: Maybe maybe not, since it was also looking for arsmagica2.SpellEffect, and that visual effect doesn't exist

http://pastebin.com/RLaBfBHe

**Comment by Zieg777** [comment]
Wasn't this fixed with the arcane guardian crash fix?

**Comment by ProfHugo** [comment]
No, the fix that was "applied" to the arcane guardian was actually just a fix to heal. The fix just stops bosses from gaining affinity and some other stuff from heal I think...

For reference: https://github.com/Growlith1223/ArsMagica2/commit/6b62bfb7b9b9b245cd31774551abacc52f330ada

**Comment by Growlith1223** [comment]
the fix was to remove the check on affinity gains. i'll check out this in a bit, im eatin lol

**Comment by Growlith1223** [comment]
this is slightly fixed, i'll come up with a better fix but for now, this seems to work.
