### ISSUE TITLE
Messed up GUI with this mod installed (1.5.0-11)

### ISSUE THREAD

**Issue by Sunconure11** [Growlith1223/ArsMagica2#97]
This issue can be replicated with AM2 alone.

I think this image is enough.

https://i.imgur.com/yg3OtAd.png

If the issue is related to Forge, I am currently on version 2185.

**Comment by garnichtpascal** [comment]
I play with ars magica 1.5.0-9 and forge 2124 and have the same bug too.

**Comment by Growlith1223** [comment]
i've fixed this, fix will be up in a few mins

**Comment by Growlith1223** [comment]
this has been fixed, new download will be up in a few mins!
